name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: |
            **/node_modules
            ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm.lock') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install Dependencies
        run: pnpm install

      - name: Build Package
        run: pnpm build:package

      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: ssc-linux
          path: ssc

  build_macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: |
            **/node_modules
            ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm.lock') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install Dependencies
        run: pnpm install

      - name: Build Package
        run: pnpm build:package

      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: ssc-macos
          path: ssc

  build_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - uses: actions/cache@v3
        id: pnpm-cache
        with:
          path: |
            **/node_modules
            ${{ steps.pnpm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm.lock') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
      - name: Install Dependencies
        run: pnpm install

      - name: Build Package
        run: pnpm build:package

      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: ssc-windows
          path: ssc.exe
